name: Build

on: [push, pull_request]

jobs:
  build:
    strategy:
      max-parallel: 10
      fail-fast: true
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        java: [adopt@1.8, adopt@1.9, adopt@1.10, adopt@1.11]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Configure git
      run: "git config --global core.autocrlf false"
      shell: bash
    - uses: actions/checkout@v1
    - name: set up JDK
      uses: actions/setup-java@v1
      with:
         java-version: 8
    - uses: olafurpg/setup-scala@v10
      with:
         java-version: ${{ matrix.java }}
    - uses: actions/checkout@master
      with:
        repository: mitre/jfastbpe
        path: ./jfastbpe
    - uses: actions/checkout@master
      with:
        repository: mitre/jfairseq
        path: ./jfairseq
    - uses: actions/checkout@master
      with:
        ref: v0.0.2
        repository: levyfan/sentencepiece-jni
        path: ./sentencepiece-jni
    - name: Setup jFastBPE
      run: cd jfastbpe && gradle test build jar publishToMavenLocal
    - name: Setup sentencepiece-jni
      run: cd sentencepiece-jni && mvn clean install
    - name: Setup jFairseq
      shell: bash
      run: cd jfairseq && sbt clean compile package publishLocal
    - name: Build
      shell: bash
      run: sbt -J-Xms1024m -J-Xmx1024m clean assembly
    - uses: actions/upload-artifact@v2
      with:
        name: omegat-torchscript ${{ matrix.os }}
        path: target/*.jar
      if: matrix.java == 'adopt@1.8'
